language: node_js

node_js:
  - '0.10'
before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

env:
  global:
    - REPO="git@github.com:g0v/sunflower"
    - secure: "J6cPxjDnCuElKAxkA8F5VgE7EJ5Uvzd0Y+fPhyu+m6C+I5014vn5ic6s6Wbz9nkDOcE979vw7KDdUfpLykWRW6bCxQKho3i3zVZjg5KZDYz9NM1ZmJfQd6NVDMH2SGn6o+KhH7mvgEl1vA2RVtDt2Ud4eBJneK1eiJAj1B8hYrA="

after_success: .travis/after_success.sh
