language: node_js

node_js:
  - '0.10'

before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

env:
  global:
    - REPO="git@github.com:g0v/sunflower"
    - secure: "AFqyb9lQmG5Q8u6Prob1sghlSkLQkxNd5KM36y96d1Gzy/R6348Hd19/Flb6upcEejLAjNnQGdyIgVICbG3yB2LvRcOg965GDa7bJERwQQU3VyrXNMlJp+xcDDYQoUJVRCdV7z2HmfuhZYOOXQhEgqfFTtjG4bGR+1TlAsJ8+kY="

after_success: .travis/after_success.sh
